apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: {{ .Values.replica }}
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
         app: app
    spec:
      containers:
      - image: ayush122001/dl_heart_app
        name: dl-heart-app-72dj4
